<a href="https://colab.research.google.com/github/aso1901103/AI_tech2020/blob/master/20201009AI0205_selectAlgo.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### sklearnでエラーが出るので、前のバージョンを入れ直す(0.22を消して0.20を入れる)

In [1]:
# # 現在のsckit-learnをcolabのVMからアンインストール
# !pip uninstall scikit-learn
# # 前のバージョンを指定してVMにインストール
# !pip install scikit-learn==0.20 --ignore-installed

### ライブラリのインポート



In [2]:
#ライブラリのインポート
import pandas as pd
#学習用とテスト用でデータを分割するらいぶらり
from sklearn.model_selection import train_test_split
#正答数を算出するライブラリ
from sklearn.metrics import accuracy_score
#all_estimators（推定器を全て使えるようになる）
from sklearn.utils.testing import all_estimators
#警告クラス
import warnings

/usr/local/lib/python3.6/dist-packages/sklearn/utils/deprecation.py:144: FutureWarning: The sklearn.utils.testing module is  deprecated in version 0.22 and will be removed in version 0.24. The corresponding classes / functions should instead be imported from sklearn.utils. Anything that cannot be imported from sklearn.utils is now part of the private API.
  warnings.warn(message, FutureWarning)


### webからアヤメのデータを読み込む

In [3]:
# urlリンクから読み込むライブラリ
import urllib.request as req
#URLの変数を定義する
url = "https://github.com/pandas-dev/pandas/raw/master/pandas/tests/io/data/csv/iris.csv"
#リンクを保存するためのファイルを定義
iris_data = "iris.csv"
req.urlretrieve(url,iris_data)
#DLしたファイルの内容を表示
#アヤメデータの読み込み
iris_data = pd.read_csv(iris_data,encoding="utf-8")
iris_data

SepalLength  SepalWidth  PetalLength  PetalWidth            Name
0            5.1         3.5          1.4         0.2     Iris-setosa
1            4.9         3.0          1.4         0.2     Iris-setosa
2            4.7         3.2          1.3         0.2     Iris-setosa
3            4.6         3.1          1.5         0.2     Iris-setosa
4            5.0         3.6          1.4         0.2     Iris-setosa
..           ...         ...          ...         ...             ...
145          6.7         3.0          5.2         2.3  Iris-virginica
146          6.3         2.5          5.0         1.9  Iris-virginica
147          6.5         3.0          5.2         2.0  Iris-virginica
148          6.2         3.4          5.4         2.3  Iris-virginica
149          5.9         3.0          5.1         1.8  Iris-virginica

[150 rows x 5 columns]

### 取得したデータの分割

In [4]:
#ラベルと入力データに分離
y = iris_data.loc[:,"Name"];
x = iris_data.loc[:,["SepalLength","SepalWidth","PetalLength","PetalWidth"]]
#学習用とテスト用に分離
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.2,train_size = 0.8, shuffle = True)

### all_estimatrosを使い学習する

In [5]:
#warningを無視する
warnings.filterwarnings('ignore')
#classifierのアルゴリズム全てを取得
allAlgrithms = all_estimators(type_filter="classifier")

for(name, algorithm) in allAlgrithms:
  #pythonでのtry-catch(try-except)
  try:
    #アルゴリズムのオブジェクトを作成
    clf = algorithm()

    #学習して評価する
    clf.fit(x_train,y_train)
    y_pred = clf.predict(x_test)
    print(name,"の正解率 = ",accuracy_score(y_test,y_pred))
  #pythonのcacth(except)
  except Exception as e:
    print("エラーです。")
    print(e)
  else:
    #print("ERROR無し")
    pass

AdaBoostClassifier の正解率 =  0.8
BaggingClassifier の正解率 =  0.8333333333333334
BernoulliNB の正解率 =  0.16666666666666666
CalibratedClassifierCV の正解率 =  0.7333333333333333
CategoricalNB の正解率 =  0.9666666666666667
エラーです。
could not convert string to float: 'Iris-setosa'
エラーです。
__init__() missing 1 required positional argument: 'base_estimator'
ComplementNB の正解率 =  0.5333333333333333
DecisionTreeClassifier の正解率 =  0.8333333333333334
DummyClassifier の正解率 =  0.2
ExtraTreeClassifier の正解率 =  0.8333333333333334
ExtraTreesClassifier の正解率 =  0.9
GaussianNB の正解率 =  0.9
GaussianProcessClassifier の正解率 =  0.9333333333333333
GradientBoostingClassifier の正解率 =  0.8333333333333334
HistGradientBoostingClassifier の正解率 =  0.8666666666666667
KNeighborsClassifier の正解率 =  0.9666666666666667
LabelPropagation の正解率 =  0.9333333333333333
LabelSpreading の正解率 =  0.9333333333333333
LinearDiscriminantAnalysis の正解率 =  0.8666666666666667
LinearSVC の正解率 =  0.8333333333333334
LogisticRegression の正解率 =  0.9333333333333333
Logis

### クロスバリデーションを行うためのライブラリをインポート

In [6]:
# クロスバリデーション関連のライブラリをインポート
# K分割クロスバリデーション（交差検証）のためのライブラリ
from sklearn.model_selection import KFold
# クロスバリデーションスコアを取得する為のオブジェクト
from sklearn.model_selection import cross_val_score


### クロスバリデーションを行う(closs_val_score)

In [7]:
# K分割交差検証のインスタンスを生成
kfold_cv = KFold(n_splits = 5, shuffle = True)
# 生成したall_estimatorsのインスタンスをループさせてクロスバリデーション
for(name, algorithm) in allAlgrithms:
  try:
    #各アルゴリズムのインスタンス
    clf = algorithm()
    #score属性のある学習モデルに絞る
    if hasattr(clf,"score"):
      #クロスバリデーションのスコアを取得
      scores = cross_val_score(clf,x,y,cv = kfold_cv)
      # k = n_splits = 5回分のクロスバリデーションスコアを表示
      print(name,"の正解率　＝　")
      print(scores)
  except Exception as e:
    #None
    pass
    print(e.args)


AdaBoostClassifier の正解率　＝　
[0.86666667 1.         0.9        0.93333333 0.96666667]
BaggingClassifier の正解率　＝　
[0.9        0.96666667 0.93333333 0.96666667 0.96666667]
BernoulliNB の正解率　＝　
[0.3        0.26666667 0.26666667 0.23333333 0.3       ]
CalibratedClassifierCV の正解率　＝　
[0.96666667 0.86666667 0.96666667 0.86666667 0.83333333]
CategoricalNB の正解率　＝　
[0.93333333 0.96666667 0.93333333 0.9        0.93333333]
CheckingClassifier の正解率　＝　
[nan nan nan nan nan]
("__init__() missing 1 required positional argument: 'base_estimator'",)
ComplementNB の正解率　＝　
[0.5        0.63333333 0.76666667 0.73333333 0.7       ]
DecisionTreeClassifier の正解率　＝　
[0.96666667 0.93333333 1.         0.96666667 0.9       ]
DummyClassifier の正解率　＝　
[0.4        0.33333333 0.43333333 0.33333333 0.36666667]
ExtraTreeClassifier の正解率　＝　
[0.86666667 0.96666667 0.96666667 0.96666667 0.96666667]
ExtraTreesClassifier の正解率　＝　
[0.93333333 1.         0.83333333 0.96666667 0.93333333]
GaussianNB の正解率　＝　
[1.         0.9        0.96666

### クロスバリデーションを行う(cross_validate)

In [8]:
# ライブラリのインポート
from sklearn.model_selection import cross_validate

In [9]:
# K分割交差検証のインスタンスを生成
kfold_cv = KFold(n_splits = 5, shuffle = True)
# 生成したall_estimatorsのインスタンスをループさせてクロスバリデーション
for(name, algorithm) in allAlgrithms:
  try:
    #各アルゴリズムのインスタンス
    clf = algorithm()
    #score属性のアル学習モデルに絞る
    if hasattr(clf,"score"):
      #クロスバリデーションのスコアを取得
      scores = cross_validate(clf,x,y,cv = kfold_cv)
      # k = n_splits = 5回分のクロスバリデーションスコアを表示
      print(name,"の正解率　＝　")
      print(scores)
  except Exception as e:
    #None
    pass
    print(e.args)

AdaBoostClassifier の正解率　＝　
{'fit_time': array([0.07338905, 0.0673697 , 0.06737971, 0.06638646, 0.07021976]), 'score_time': array([0.0069952 , 0.00749516, 0.00709486, 0.00681281, 0.008219  ]), 'test_score': array([0.96666667, 0.93333333, 0.93333333, 0.96666667, 0.9       ])}
BaggingClassifier の正解率　＝　
{'fit_time': array([0.01578569, 0.01401639, 0.01432538, 0.01396799, 0.01438022]), 'score_time': array([0.00214624, 0.00211716, 0.00208831, 0.00216317, 0.00218582]), 'test_score': array([0.93333333, 0.86666667, 0.93333333, 1.        , 0.96666667])}
BernoulliNB の正解率　＝　
{'fit_time': array([0.00337601, 0.00197029, 0.00187922, 0.00188494, 0.00188327]), 'score_time': array([0.00106359, 0.00108767, 0.00096655, 0.00095844, 0.00097132]), 'test_score': array([0.23333333, 0.23333333, 0.33333333, 0.26666667, 0.33333333])}
CalibratedClassifierCV の正解率　＝　
{'fit_time': array([0.0594151 , 0.06091261, 0.06114984, 0.05913329, 0.058676  ]), 'score_time': array([0.00345063, 0.00180173, 0.00189543, 0.00190234, 0

### グリッドサーチで最適なパラメータを探索する
ライブラリをインポート



In [10]:
#グリッドサーチのオブジェクトクラスをインポート
from sklearn.model_selection import GridSearchCV
from sklearn.svm import SVC

### グリッドサーチを実行してパラメータを取得



In [11]:
# グリッドサーチで試すパラメータのパターン指定を定義する
parameters = [
              # 3つのパラメータ、3パターン
              {"C":[1,10,100,1000],"kernel":["linear"]},
              {"C":[1,10,100,1000],"kernel":["rbf"],"gamma":[0.001,0.0001]},
              {"C":[1,10,100,1000],"kernel":["sigmoid"],"gamma":[0.001,0.0001]}
]

#normal learn
clf = SVC()
clf.fit(x_train,y_train)
y_pred = clf.predict(x_test)
print("普通の学習の正解率　＝　",accuracy_score(y_test,y_pred))

# run grid search 
# make of Ksplit cross validate instance
kfold_cv = KFold(n_splits=5,shuffle=True)

#run k split cross validate in grid search
clf_grid = GridSearchCV(SVC(),parameters,cv = kfold_cv)
clf_grid.fit(x_train,y_train)

#Already learned model set last parametor,and print
print("最適なパラメータ　=　",clf_grid.best_estimator_)

#model already set best parametor to evolve
y_pred = clf_grid.predict(x_test)
print ("グリッドサーチの正解率 = ",accuracy_score(y_test,y_pred))


普通の学習の正解率　＝　 0.9333333333333333
最適なパラメータ　=　 SVC(C=1, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='linear',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)
グリッドサーチの正解率 =  0.9666666666666667


### Numpyの動作確認



In [12]:
import numpy as np

# numpy配列の初期化
#ndarrayというnumpy配列を生成
a = np.array([1,2,3,4,5])
print(a)
#type関数で関数型を表示
print(type(a))



[1 2 3 4 5]
<class 'numpy.ndarray'>


In [13]:
#2次元配列のndarrayを定義
b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [14]:
#配列の要素数を指定して初期化状態で作成
#1次元配列
print(np.zeros(10))
#2次元配列
print(np.zeros((3,2)))
#配列の中身を１で初期化
print(np.ones(3))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[0. 0.]
 [0. 0.]
 [0. 0.]]
[1. 1. 1.]


In [15]:
#配列を要素数を指定して初期化
print(np.arange(5))
print(np.arange(2,4))
print( np.arange(5, 8, 0.5) )

[0 1 2 3 4]
[2 3]
[5.  5.5 6.  6.5 7.  7.5]


### numpyで行列計算



In [16]:
a = np.array( [1, 2, 3, 4, 5] )
b = a*2 # 全ての要素を一度に2倍
print(b)
x = np.arange(10)
print(x)
y = 3*x + 5 # 全ての要素に一度に四則演算
print(y)

[ 2  4  6  8 10]
[0 1 2 3 4 5 6 7 8 9]
[ 5  8 11 14 17 20 23 26 29 32]


In [17]:
# 配列の次元数を表示
a = np.array( [[1, 2, 3], [4, 5, 6]] )
print(a)
print(a.shape)

b = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(b)
print(b.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)
[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)


In [18]:
# Numpy配列で次元数を変換する
a = np.array( [[1, 2, 3], [4, 5, 6]] )
print("a = ", a, "\n")
b = a.flatten() # フラットにする(1次元配列にする)
print("b = ", b, "\n")

a = np.array( [[1, 2, 3], [4, 5, 6]] ) # ２行3列
print(a, "\n")
b = a.reshape(3,2) # 3行2列に回転(変換)
print(b)

a =  [[1 2 3]
 [4 5 6]] 

b =  [1 2 3 4 5 6] 

[[1 2 3]
 [4 5 6]] 

[[1 2]
 [3 4]
 [5 6]]


In [19]:
# 配列の参照
v = np.array( [[1, 2, 3], [4, 5, 6], [7, 8, 9]] )
a = v[0]
print(a, "\n") # 2次元配列の0行目
b = v[1:]
print(b, "\n") # 1行目以降
c = v[:, 0]
print(c) # 全ての行の0列目

[1 2 3] 

[[4 5 6]
 [7 8 9]] 

[1 4 7]
